### ISSUE TITLE
gstplayer broken on wayland

### ISSUE THREAD

**Issue by albfan** [albfan/miraclecast#183]
```
$ gstplayer
Traceback (most recent call last):
  File "/usr/local/bin/gstplayer", line 229, in <module>
    p.run()
  File "/usr/local/bin/gstplayer", line 179, in run
    self.xid = self.drawingarea.get_property('window').get_xid()
AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'
```

**Comment by albfan** [comment]
By now it can be workaround with:

    $ GDK_BACKEND=x11 gstplayer

but there must be a proper fix, so I will keep this open

**Comment by albfan** [comment]
xid is the id for x11 so makes sense there's no such thing on Wayland.

Here are examples for same funcionality with new api:

https://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/tests/examples/gtk

gstsink should work with wayland (changing whatever neccesary)

**Comment by albfan** [comment]
Meanwhile migration to Wayland is done adding this to init scripts (see #89) 

```
if [ -n "$DISPLAY" -a -z "$SSH_CLIENT" ]; then
    xhost +si:localuser:root
fi
```

should work

**Comment by orowith2os** [comment]
You can fix this properly by using the ScreenCast portal, and passing the pipewire stream to gstreamer.

**Comment by albfan** [comment]
That's the idea. Do we have any Python example?

C implementation should be easy to translate but still any example would be helpful

**Comment by orowith2os** [comment]
You can find libportal test apps here, but the dbus documentation for the portals themselves are fairly simple.

https://github.com/flatpak/libportal/tree/main/portal-test

**Comment by albfan** [comment]
I'm just rereading the issue: This is not about sharing the screen, as gstplayer plays the stream from the other device.

This is about gstplayer is implemented with x11 windows instead of wayland window.

If you agree, will remove our comments as they are misleading

**Comment by orowith2os** [comment]
Ah, yeah, misunderstood. Go ahead.

**Comment by albfan** [comment]
Definitely will need this on #4. Add a comment if you can please
